server:
  ssl:
    enabled: false
  tomcat:
    accesslog:
      enabled: false

spring:
  cloud:
    zookeeper:
      connect-string: 192.168.1.107:2181 # "Spring Cloud" magic property "spring.cloud.zookeeper.connect-string"
  norpc-security:
    cookieName: ExtAuthToken
    rememberMeKey: U178_0y9#
    rememberMeLifeSeconds: 604800 # 7*24*60*60
    jasyptSymmetricSecret: abcdef
  security:
    cookieName: remember-me
    usernameParameter: principal
    rememberMeKey: Y1#n8_0x_22E#
    rememberMeLifeSeconds: 604800 # 7*24*60*60
    targetUrlParameter: targetUrl
    defaultAuthEndpoint: http://localhost:10570/login
  rwds:
    master:
      username: root
      password:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.1.132:3307/exam
    slaveList:
      - username: root
        password:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.1.132:3307/exam # ShardingSphere MasterSlaveDataSource requires non-empty slave list